[package]
name = "heddle-iroh-transport-experiment"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
api = { package = "heddle-api", version = "0.2.1" }
bytes.workspace = true
iroh.workspace = true
objects.workspace = true
prost.workspace = true
thiserror.workspace = true
tokio.workspace = true
wire = { workspace = true, features = ["zstd"] }

[dev-dependencies]
tempfile.workspace = true

[lib]
path = "src/lib.rs"
