[package]
name = "heddle-cli-args"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Heddle's command-line argument surface."
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
anyhow.workspace = true
api = { package = "heddle-api", version = "0.10" }
clap.workspace = true
config = { path = "../config", package = "heddle-config", version = "0.13" }
objects = { path = "../objects", package = "heddle-objects", version = "0.13" }
repo = { path = "../repo", package = "heddle-repo", version = "0.13", default-features = false, features = ["git-overlay", "native"] }

[features]
default = []
ci = []
client = []
git-overlay = []
ingest = []
semantic = []

[lib]
path = "src/lib.rs"
name = "heddle_cli_args"
