// SPDX-License-Identifier: Apache-2.0
//! Generate TypeScript types from heddle's runtime JSON-Schema introspection.
//!
//! This is the source of truth for the `clients/npm` wrapper (#581/#584): it
//! walks every schema verb ([`schema_verbs`]), renders the schemars-derived
//! JSON Schema for each ([`schema_for_verb`]), and produces both the raw
//! schemas and hand-free TypeScript declarations a Node/Electron harness can
//! import.
//!
//! The output is deterministic (everything sorted), so regenerating on an
//! unchanged contract produces a no-op diff. The `gen_ts_types` example writes
//! it to disk; `tests/ts_types_in_sync.rs` asserts the checked-in files match.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use serde_json::{Map, Value};

use crate::cli::commands::{schema_for_verb, schema_verbs};

/// Schema-contract version the emitted types are pinned to. Tracks the
/// `heddle-cli` crate version: a contract change ships in a new CLI release,
/// so the crate version is the coarsest-correct pin for "which heddle do
/// these types describe".
pub const SCHEMA_VERSION: &str = env!("CARGO_PKG_VERSION");

/// The generated wrapper artifacts.
pub struct Generated {
    /// `heddle-schemas.ts` — TypeScript types + verb map + version pin.
    pub typescript: String,
    /// `heddle-schemas.json` — raw JSON Schemas keyed by verb.
    pub json: String,
}

/// Render the TypeScript module and raw-schema JSON from the live catalog.
pub fn generate() -> Generated {
    // name -> type body. `$defs` populate first; a verb's own root overlays its
    // matching name (the root carries runtime-injected op_id / discriminator
    // fields that the same struct-as-a-$def elsewhere lacks).
    let mut types: BTreeMap<String, Value> = BTreeMap::new();
    let mut roots: BTreeMap<String, Value> = BTreeMap::new();
    let mut verb_to_type: BTreeMap<String, String> = BTreeMap::new();
    let mut raw: BTreeMap<String, Value> = BTreeMap::new();

    let mut verbs: Vec<&str> = schema_verbs().to_vec();
    verbs.sort_unstable();

    for verb in verbs {
        let Some(schema) = schema_for_verb(verb) else {
            continue;
        };

        if let Some(defs) = schema.get("$defs").and_then(Value::as_object) {
            for (name, body) in defs {
                types
                    .entry(sanitize_ident(name))
                    .or_insert_with(|| body.clone());
            }
        }

        let title = schema
            .get("title")
            .and_then(Value::as_str)
            .map(sanitize_ident)
            .unwrap_or_else(|| verb_type_name(verb));
        roots.insert(title.clone(), strip_root_meta(&schema));
        verb_to_type.insert(verb.to_string(), title);
        raw.insert(verb.to_string(), schema);
    }

    // Roots win over same-named `$defs`.
    for (name, body) in &roots {
        types.insert(name.clone(), body.clone());
    }

    let typescript = render_ts(&types, &verb_to_type);
    let json = serde_json::to_string_pretty(&serde_json::json!({
        "schemaVersion": SCHEMA_VERSION,
        "verbs": raw,
    }))
    .expect("raw schemas serialize")
        + "\n";

    Generated { typescript, json }
}

/// Drop the JSON-Schema envelope keys, keeping only the type body so a root
/// can be emitted exactly like a `$def`.
fn strip_root_meta(schema: &Value) -> Value {
    let Some(obj) = schema.as_object() else {
        return schema.clone();
    };
    let mut out = Map::new();
    for (k, v) in obj {
        if matches!(k.as_str(), "$schema" | "$defs" | "title") {
            continue;
        }
        out.insert(k.clone(), v.clone());
    }
    Value::Object(out)
}

fn render_ts(types: &BTreeMap<String, Value>, verb_to_type: &BTreeMap<String, String>) -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by `cargo run -p heddle-cli --example gen_ts_types` — DO NOT EDIT.\n");
    out.push_str("// Source of truth: heddle's runtime JSON-Schema introspection\n");
    out.push_str("// (`heddle schemas <verb>` / `crates/cli/src/cli/commands/schemas.rs`).\n");
    out.push_str("// Regenerate with `scripts/gen-ts-types.sh`; a drift test keeps it in sync.\n\n");
    let _ = writeln!(
        out,
        "export const HEDDLE_SCHEMA_VERSION = {:?} as const;\n",
        SCHEMA_VERSION
    );

    for (name, body) in types {
        emit_type(&mut out, name, body);
    }

    out.push_str("/** Maps each `--output json` verb to its output payload type. */\n");
    out.push_str("export interface HeddleVerbOutputs {\n");
    for (verb, ty) in verb_to_type {
        let _ = writeln!(out, "  {}: {};", quote_key(verb), ty);
    }
    out.push_str("}\n\n");

    out.push_str("/** Every verb that emits a schema-backed `--output json` payload. */\n");
    out.push_str("export type HeddleSchemaVerb = keyof HeddleVerbOutputs;\n\n");

    out.push_str("export const HEDDLE_SCHEMA_VERBS: readonly HeddleSchemaVerb[] = [\n");
    for verb in verb_to_type.keys() {
        let _ = writeln!(out, "  {},", json_string(verb));
    }
    out.push_str("] as const;\n");

    out
}

fn emit_type(out: &mut String, name: &str, body: &Value) {
    let is_object = body.get("type").and_then(Value::as_str) == Some("object")
        && body.get("properties").is_some();

    if let Some(desc) = body.get("description").and_then(Value::as_str) {
        emit_jsdoc(out, desc, "");
    }

    if is_object {
        let _ = writeln!(out, "export interface {name} {{");
        emit_object_body(out, body, "  ");
        out.push_str("}\n\n");
    } else {
        let _ = writeln!(out, "export type {name} = {};\n", ts_type(body));
    }
}

/// Emit the fields of an object schema into an already-open `{ ... }` block.
fn emit_object_body(out: &mut String, body: &Value, indent: &str) {
    let required: Vec<&str> = body
        .get("required")
        .and_then(Value::as_array)
        .map(|a| a.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();

    if let Some(props) = body.get("properties").and_then(Value::as_object) {
        for (field, schema) in props {
            if let Some(desc) = schema.get("description").and_then(Value::as_str) {
                emit_jsdoc(out, desc, indent);
            }
            let opt = if required.contains(&field.as_str()) {
                ""
            } else {
                "?"
            };
            let _ = writeln!(out, "{indent}{}{opt}: {};", quote_key(field), ts_type(schema));
        }
    }

    // Open record / flattened-map shapes.
    match body.get("additionalProperties") {
        Some(Value::Bool(true)) => {
            let _ = writeln!(out, "{indent}[key: string]: unknown;");
        }
        Some(v @ Value::Object(_)) => {
            let _ = writeln!(out, "{indent}[key: string]: {};", ts_type(v));
        }
        _ => {}
    }
}

/// Convert a JSON-Schema node into a TypeScript type expression.
fn ts_type(node: &Value) -> String {
    match node {
        Value::Bool(true) => return "unknown".to_string(),
        Value::Bool(false) => return "never".to_string(),
        _ => {}
    }
    let Some(obj) = node.as_object() else {
        return "unknown".to_string();
    };

    if let Some(reference) = obj.get("$ref").and_then(Value::as_str) {
        return ref_name(reference);
    }

    if let Some(values) = obj.get("enum").and_then(Value::as_array) {
        let mut parts: Vec<String> = values.iter().map(literal).collect();
        parts.dedup();
        return parts.join(" | ");
    }

    for key in ["anyOf", "oneOf"] {
        if let Some(variants) = obj.get(key).and_then(Value::as_array) {
            let mut parts: Vec<String> = variants.iter().map(ts_type).collect();
            parts.dedup();
            return union(parts);
        }
    }

    if let Some(all) = obj.get("allOf").and_then(Value::as_array) {
        let parts: Vec<String> = all.iter().map(ts_type).collect();
        return parts.join(" & ");
    }

    match obj.get("type") {
        Some(Value::String(t)) => ts_scalar(t, obj),
        Some(Value::Array(kinds)) => {
            let mut parts: Vec<String> = kinds
                .iter()
                .filter_map(Value::as_str)
                .map(|t| ts_scalar(t, obj))
                .collect();
            parts.dedup();
            union(parts)
        }
        _ => {
            if obj.contains_key("properties") || obj.contains_key("additionalProperties") {
                inline_object(obj)
            } else {
                "unknown".to_string()
            }
        }
    }
}

fn ts_scalar(t: &str, obj: &Map<String, Value>) -> String {
    match t {
        "string" => "string".to_string(),
        "integer" | "number" => "number".to_string(),
        "boolean" => "boolean".to_string(),
        "null" => "null".to_string(),
        "array" => {
            let item = obj
                .get("items")
                .map(ts_type)
                .unwrap_or_else(|| "unknown".to_string());
            if item.contains(' ') || item.contains('|') || item.contains('&') {
                format!("({item})[]")
            } else {
                format!("{item}[]")
            }
        }
        "object" => inline_object(obj),
        other => format!("unknown /* {other} */"),
    }
}

fn inline_object(obj: &Map<String, Value>) -> String {
    if obj.get("properties").and_then(Value::as_object).is_none() {
        return match obj.get("additionalProperties") {
            Some(v @ Value::Object(_)) => format!("Record<string, {}>", ts_type(v)),
            _ => "Record<string, unknown>".to_string(),
        };
    }
    let body = Value::Object(obj.clone());
    let mut inner = String::new();
    emit_object_body(&mut inner, &body, "");
    let fields: Vec<&str> = inner
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty())
        .collect();
    format!("{{ {} }}", fields.join(" "))
}

fn union(mut parts: Vec<String>) -> String {
    parts.retain(|p| !p.is_empty());
    if parts.is_empty() {
        return "unknown".to_string();
    }
    parts.join(" | ")
}

fn ref_name(reference: &str) -> String {
    let raw = reference.rsplit('/').next().unwrap_or(reference);
    sanitize_ident(raw)
}

fn literal(v: &Value) -> String {
    match v {
        Value::String(s) => json_string(s),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => n.to_string(),
        Value::Null => "null".to_string(),
        other => json_string(&other.to_string()),
    }
}

fn json_string(s: &str) -> String {
    Value::String(s.to_string()).to_string()
}

/// Object keys that are valid bare TS identifiers stay bare; everything else
/// (verbs with spaces, etc.) gets quoted.
fn quote_key(key: &str) -> String {
    let bare = !key.is_empty()
        && key
            .chars()
            .enumerate()
            .all(|(i, c)| c == '_' || c.is_ascii_alphabetic() || (i > 0 && c.is_ascii_digit()));
    if bare {
        key.to_string()
    } else {
        json_string(key)
    }
}

fn sanitize_ident(name: &str) -> String {
    let mut out: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

fn verb_type_name(verb: &str) -> String {
    let camel: String = verb
        .split([' ', '-', '_'])
        .filter(|s| !s.is_empty())
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect();
    format!("{camel}Schema")
}

fn emit_jsdoc(out: &mut String, desc: &str, indent: &str) {
    let one_line = desc.split_whitespace().collect::<Vec<_>>().join(" ");
    let safe = one_line.replace("*/", "*\\/");
    let _ = writeln!(out, "{indent}/** {safe} */");
}
