[package]
name = "capability-verifier-conformance-native"
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
publish = false

[dependencies]
heddleco-capability-verifier = { path = "../.." }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[workspace]

[patch.crates-io]
heddle-api = { git = "https://github.com/HeddleCo/api.git", rev = "6ef425d8c688988888881898a36258cff6645b26", version = "0.31.0-alpha.1" }
