[package]
name = "capability-verifier-conformance-native"
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
publish = false

[dependencies]
heddleco-capability-verifier = { path = "../.." }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"
prost = "0.14"
ed25519-dalek = "3"
heddle-api = "=0.31.0-alpha.45"

[workspace]

[patch.crates-io]
heddle-api = { git = "https://github.com/HeddleCo/api", rev = "a1a4b6e34fc0737bc0cad3d388cc4a2e3fe28dae", version = "=0.31.0-alpha.45" }
