#!/usr/bin/env python3
"""Generate docs/program/cli-domain-residual.md — CLI cmd_* modules not yet thin.

Heuristic: list Rust sources under crates/cli/src that define `fn cmd_` and
report LOC + whether they import heddle_core. Used to order Wave 3+ extraction.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CLI_SRC = ROOT / "crates" / "cli" / "src"
OUT = ROOT / "docs" / "program" / "cli-domain-residual.md"

CMD_RE = re.compile(r"\b(?:pub\s+)?(?:async\s+)?fn\s+(cmd_\w+)\s*\(")
CORE_RE = re.compile(r"\bheddle_core\b|use\s+heddle_core")


def main() -> None:
    rows = []
    for path in sorted(CLI_SRC.rglob("*.rs")):
        text = path.read_text(errors="ignore")
        cmds = CMD_RE.findall(text)
        if not cmds:
            continue
        rel = path.relative_to(ROOT).as_posix()
        loc = text.count("\n") + 1
        uses_core = bool(CORE_RE.search(text))
        rows.append(
            {
                "path": rel,
                "loc": loc,
                "cmds": sorted(set(cmds)),
                "uses_core": uses_core,
            }
        )
    rows.sort(key=lambda r: (-r["loc"], r["path"]))

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "# CLI domain residual matrix",
        "",
        f"Generated by `scripts/program/gen-cli-domain-residual.py` at {stamp}.",
        "",
        "Heuristic only: files under `crates/cli/src` defining `fn cmd_*`, sorted by LOC.",
        "`uses_heddle_core` means the file imports the facade (not that the command is fully extracted).",
        "",
        "| LOC | uses_heddle_core | path | cmd_* |",
        "|----:|:----------------:|------|-------|",
    ]
    for r in rows:
        cmds = ", ".join(f"`{c}`" for c in r["cmds"][:8])
        if len(r["cmds"]) > 8:
            cmds += f", … (+{len(r['cmds']) - 8})"
        lines.append(
            f"| {r['loc']} | {'yes' if r['uses_core'] else 'no'} | `{r['path']}` | {cmds} |"
        )
    lines.extend(
        [
            "",
            f"**Total files with cmd_*:** {len(rows)}",
            f"**Total LOC in those files:** {sum(r['loc'] for r in rows)}",
            "",
            "## Suggested extraction order",
            "",
            "Prefer high-LOC modules with `uses_heddle_core=no` that implement durable VCS",
            "semantics (thread lifecycle, remotes, undo, clone) over pure render/catalog modules.",
            "",
        ]
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(rows)} files)")


if __name__ == "__main__":
    main()
