#!/usr/bin/env python3
"""Generate architecture inventories for ambient state and process spawns.

Writes:
  docs/program/inventory-ambient-state.md
  docs/program/inventory-process-spawns.md
"""

from __future__ import annotations

import re
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CRATES = ROOT / "crates"

AMBIENT_RES = [
    re.compile(r"\bOnceLock\b"),
    re.compile(r"\blazy_static!\b"),
    re.compile(r"\bthread_local!\b"),
    re.compile(r"static\s+mut\b"),
    re.compile(r"static\s+[A-Z_][A-Z0-9_]*\s*:\s*"),
]
SPAWN_RE = re.compile(
    r"""(?:std::process::|tokio::process::)?Command::new\s*\(\s*(?P<arg>[^)]+)\)"""
)
CFG_TEST = re.compile(r"#\[cfg\(test\)\]")


def is_testish(path: Path, line_no: int, lines: list[str]) -> bool:
    rel = path.as_posix()
    if path.name.endswith("_tests.rs") or path.name == "tests.rs" or "/tests/" in rel:
        return True
    # Walk backward for #[cfg(test)] mod tests {
    for i in range(line_no - 1, max(-1, line_no - 400), -1):
        if i < 0:
            break
        if "mod tests" in lines[i] and i > 0 and "#[cfg(test)]" in lines[i - 1]:
            return True
        if CFG_TEST.search(lines[i]) and i + 1 < len(lines) and "mod tests" in lines[i + 1]:
            return True
    return False


def scan_ambient() -> list[dict]:
    hits = []
    for path in sorted(CRATES.rglob("*.rs")):
        if "target" in path.parts:
            continue
        text = path.read_text(errors="ignore")
        lines = text.splitlines()
        for i, line in enumerate(lines, 1):
            for rx in AMBIENT_RES:
                if rx.search(line):
                    # Skip pure re-exports of OnceLock type in use lines without static
                    if "use " in line and "OnceLock" in line and "static" not in line:
                        continue
                    hits.append(
                        {
                            "path": path.relative_to(ROOT).as_posix(),
                            "line": i,
                            "kind": rx.pattern,
                            "snippet": line.strip()[:160],
                            "testish": is_testish(path, i, lines),
                        }
                    )
                    break
    return hits


def scan_spawns() -> list[dict]:
    hits = []
    for path in sorted(CRATES.rglob("*.rs")):
        if "target" in path.parts:
            continue
        text = path.read_text(errors="ignore")
        lines = text.splitlines()
        for i, line in enumerate(lines, 1):
            m = SPAWN_RE.search(line)
            if not m:
                continue
            hits.append(
                {
                    "path": path.relative_to(ROOT).as_posix(),
                    "line": i,
                    "arg": m.group("arg").strip()[:80],
                    "snippet": line.strip()[:160],
                    "testish": is_testish(path, i, lines),
                }
            )
    return hits


def write_ambient(hits: list[dict]) -> None:
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    prod = [h for h in hits if not h["testish"]]
    lines = [
        "# Ambient state inventory",
        "",
        f"Generated by `scripts/program/gen-architecture-inventory.py` at {stamp}.",
        "",
        f"Production-ish hits: **{len(prod)}** (test modules filtered heuristically).",
        "",
        "| path | line | kind | snippet |",
        "|------|-----:|------|---------|",
    ]
    for h in sorted(prod, key=lambda x: (x["path"], x["line"])):
        snip = h["snippet"].replace("|", "\\|")
        lines.append(f"| `{h['path']}` | {h['line']} | `{h['kind']}` | `{snip}` |")
    out = ROOT / "docs" / "program" / "inventory-ambient-state.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(prod)} prod hits / {len(hits)} total)")


def write_spawns(hits: list[dict]) -> None:
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    prod = [h for h in hits if not h["testish"]]
    by_arg: dict[str, list] = defaultdict(list)
    for h in prod:
        by_arg[h["arg"]].append(h)
    lines = [
        "# Process spawn inventory",
        "",
        f"Generated by `scripts/program/gen-architecture-inventory.py` at {stamp}.",
        "",
        f"Production-ish Command::new sites: **{len(prod)}**.",
        "",
        "## By command argument",
        "",
    ]
    for arg, group in sorted(by_arg.items(), key=lambda kv: (-len(kv[1]), kv[0])):
        lines.append(f"### `{arg}` ({len(group)})")
        lines.append("")
        for h in group:
            lines.append(f"- `{h['path']}:{h['line']}` — `{h['snippet']}`")
        lines.append("")
    out = ROOT / "docs" / "program" / "inventory-process-spawns.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(prod)} prod hits / {len(hits)} total)")


def main() -> None:
    write_ambient(scan_ambient())
    write_spawns(scan_spawns())


if __name__ == "__main__":
    main()
