[package]
name = "heddle-state-review"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
objects.workspace = true
repo = { workspace = true, features = ["default", "tree-sitter-symbols"] }
tracing.workspace = true
semantic.workspace = true
serde.workspace = true

[lib]
path = "src/lib.rs"
name = "state_review"

[dev-dependencies]
tempfile.workspace = true
