#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate docs/llms.txt and docs/llms-full.txt from the Heddle docs corpus.

`llms.txt`      — a concise, agent-facing index of the top-level docs with a
                  one-line description and relative link for each file.
`llms-full.txt` — the concatenated corpus (every top-level `docs/*.md`), so an
                  agent can slurp the whole reference set in one fetch.

Both follow the emerging llms.txt convention (https://llmstxt.org/). They cover
only the top-level `docs/*.md` reference set — the deep subtrees (`adr/`,
`spikes/`, `perf/`, `benchmarks/`, `program/`, `design/`, `contributor-guide/`,
`agents/`) are listed as reference directories in the index but not inlined, to
keep the corpus focused on the durable, human-authored reference docs.

Usage:
    scripts/gen-llms-txt.py            # (re)write the two files
    scripts/gen-llms-txt.py --check    # exit 1 if the committed files are stale

Run this whenever docs/*.md changes; the outputs are committed to the repo.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = REPO_ROOT / "docs"

INDEX_PATH = DOCS_DIR / "llms.txt"
FULL_PATH = DOCS_DIR / "llms-full.txt"

PROJECT_NAME = "Heddle"
BLURB = (
    "Agent-native version control. Heddle is built around saved states and "
    "isolated threads with signed provenance, and exposes a stable JSON machine "
    "contract (`--output json`) so agents can drive it without parsing prose. "
    "Git compatibility is an interop/output layer, not the core model."
)
INTRO = (
    "This index covers Heddle's top-level reference docs. Start an agent at "
    "`heddle help model` for the mental model and `heddle help --output json` "
    "for the machine-readable command catalog; the docs below carry the durable "
    "contracts (exit codes, JSON schemas, stability guarantees, auth model)."
)

# Reference subtrees that are indexed as directories but not inlined into the
# full corpus. (label, one-line description)
REFERENCE_DIRS = [
    ("adr/", "Architecture Decision Records."),
    ("agents/", "Per-repo agent operating config (issue tracker, domain docs)."),
    ("design/", "Design notes and proposals."),
    ("contributor-guide/", "Contributor onboarding and workflow guides."),
    ("perf/", "Performance investigations and profiles."),
    ("benchmarks/", "Benchmark harness notes and results."),
    ("spikes/", "Exploratory spikes and prototypes."),
    ("program/", "Program-level planning docs."),
]

_MD_LINK = re.compile(r"\[([^\]]+)\]\([^)]+\)")
_MD_EMPH = re.compile(r"[*_`]+")


def _clean(text: str) -> str:
    text = _MD_LINK.sub(r"\1", text)
    text = _MD_EMPH.sub("", text)
    return text.strip()


def _title_and_desc(md_path: Path) -> tuple[str, str]:
    """First `# ` heading as title; first prose line after it as description."""
    title = md_path.stem
    desc = ""
    seen_title = False
    for raw in md_path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not seen_title:
            if line.startswith("# "):
                title = _clean(line[2:])
                seen_title = True
            continue
        # after the title: find the first meaningful prose line
        if not line:
            continue
        if line.startswith("#"):
            continue
        candidate = _clean(line.lstrip("> ").strip())
        if candidate:
            desc = candidate
            break
    if len(desc) > 160:
        desc = desc[:157].rstrip() + "..."
    return title, desc


def _corpus() -> list[Path]:
    return sorted(p for p in DOCS_DIR.glob("*.md") if p.name not in {"llms.txt"})


def build_index(files: list[Path]) -> str:
    out: list[str] = []
    out.append(f"# {PROJECT_NAME}")
    out.append("")
    out.append(f"> {BLURB}")
    out.append("")
    out.append(INTRO)
    out.append("")
    out.append("## Docs")
    out.append("")
    for f in files:
        title, desc = _title_and_desc(f)
        suffix = f": {desc}" if desc else ""
        out.append(f"- [{title}]({f.name}){suffix}")
    out.append("")
    out.append("## Reference directories")
    out.append("")
    out.append(
        "Not inlined into `llms-full.txt`; browse in-repo under `docs/`."
    )
    out.append("")
    for label, desc in REFERENCE_DIRS:
        out.append(f"- [{label}]({label}): {desc}")
    out.append("")
    return "\n".join(out)


def build_full(files: list[Path]) -> str:
    out: list[str] = []
    out.append(f"# {PROJECT_NAME} documentation — full corpus")
    out.append("")
    out.append(
        "Generated by scripts/gen-llms-txt.py from docs/*.md. Do not edit by "
        "hand; edit the source docs and regenerate."
    )
    out.append("")
    for f in files:
        rel = f.relative_to(REPO_ROOT).as_posix()
        out.append("=" * 72)
        out.append(f"Source: {rel}")
        out.append("=" * 72)
        out.append("")
        out.append(f.read_text(encoding="utf-8").rstrip("\n"))
        out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if committed outputs differ from a fresh render",
    )
    args = parser.parse_args()

    files = _corpus()
    if not files:
        print("no docs/*.md found", file=sys.stderr)
        return 1

    index = build_index(files)
    full = build_full(files)

    if args.check:
        stale = []
        for path, content in ((INDEX_PATH, index), (FULL_PATH, full)):
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current != content:
                stale.append(path.relative_to(REPO_ROOT).as_posix())
        if stale:
            print(
                "stale (run scripts/gen-llms-txt.py): " + ", ".join(stale),
                file=sys.stderr,
            )
            return 1
        print("llms.txt / llms-full.txt are up to date")
        return 0

    INDEX_PATH.write_text(index, encoding="utf-8")
    FULL_PATH.write_text(full, encoding="utf-8")
    print(
        f"wrote {INDEX_PATH.relative_to(REPO_ROOT)} "
        f"({len(index)} bytes) and "
        f"{FULL_PATH.relative_to(REPO_ROOT)} ({len(full)} bytes) "
        f"from {len(files)} docs"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
