[package]
name = "heddle-crypto"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
aes-gcm.workspace = true
base64.workspace = true
chrono.workspace = true
ed25519-dalek.workspace = true
getrandom.workspace = true
hex.workspace = true
hkdf.workspace = true
objects.workspace = true
p256.workspace = true
pkcs8.workspace = true
sec1.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
x25519-dalek.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lib]
path = "src/lib.rs"
name = "crypto"
