[package]
name = "heddle-refs"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
chrono.workspace = true
fs2.workspace = true
heddle-object-model = { path = "../object-model", version = "0.14" }
heddle-perf-contract = { path = "../perf-contract", version = "0.14" }
objects = { path = "../objects", package = "heddle-objects", version = "0.14" }
rand.workspace = true
rmp-serde.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true


[dev-dependencies]
pollster = "0.4"
tempfile.workspace = true

[features]

[lib]
path = "src/lib.rs"
name = "refs"
